name: softbenz_task
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  logger: ^2.5.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  dartz: ^0.10.1
  flutter_bloc: ^9.0.0
  json_annotation: ^4.9.0
  bloc_concurrency: ^0.3.0
  flutter_gen_runner: ^5.9.0
  flutter_svg: ^2.0.17
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  expandable: ^5.0.1
  flutter_html: ^3.0.0-beta.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1


flutter_gen:
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3


flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/



  fonts:
    - family: BarlowBold
      fonts:
        - asset: assets/fonts/Barlow-Bold.ttf
    - family: BarlowSemiBold
      fonts:
        - asset: assets/fonts/Barlow-SemiBold.ttf
    - family: BarlowMedium
      fonts:
        - asset: assets/fonts/Barlow-Medium.ttf
    - family: BarlowRegular
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf


