// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMZpp9H_nEt_-ZbRGDB_pbQccyLU3K59k',
    appId: '1:80092329722:web:378ab1ecb1253cc2b77b43',
    messagingSenderId: '80092329722',
    projectId: 'push-notification-softbenz',
    authDomain: 'push-notification-softbenz.firebaseapp.com',
    storageBucket: 'push-notification-softbenz.firebasestorage.app',
    measurementId: 'G-1ZD1M0567X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyzzBe4hyeDvEmBqrnWWWKwHFHF3rcblQ',
    appId: '1:80092329722:android:81b13162df25933db77b43',
    messagingSenderId: '80092329722',
    projectId: 'push-notification-softbenz',
    storageBucket: 'push-notification-softbenz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIP-barDOTc6MyhZqYQ6P696SIPW5pITo',
    appId: '1:80092329722:ios:ca44e3050880c79cb77b43',
    messagingSenderId: '80092329722',
    projectId: 'push-notification-softbenz',
    storageBucket: 'push-notification-softbenz.firebasestorage.app',
    iosBundleId: 'com.example.softbenzTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIP-barDOTc6MyhZqYQ6P696SIPW5pITo',
    appId: '1:80092329722:ios:ca44e3050880c79cb77b43',
    messagingSenderId: '80092329722',
    projectId: 'push-notification-softbenz',
    storageBucket: 'push-notification-softbenz.firebasestorage.app',
    iosBundleId: 'com.example.softbenzTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMZpp9H_nEt_-ZbRGDB_pbQccyLU3K59k',
    appId: '1:80092329722:web:53e4a459a03d57a9b77b43',
    messagingSenderId: '80092329722',
    projectId: 'push-notification-softbenz',
    authDomain: 'push-notification-softbenz.firebaseapp.com',
    storageBucket: 'push-notification-softbenz.firebasestorage.app',
    measurementId: 'G-G2RTF84HYS',
  );
}
